In [2]:
import pandas as pd

In [3]:
data = pd.read_csv(r"E:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\notebooks\data\UCI_Credit_Card.csv")

In [4]:
columns_to_drop = ["ID", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"]
data = data.drop(columns=columns_to_drop)

In [5]:
duplicates_count = data.duplicated().sum()
print(f"Number of duplicates: {duplicates_count}")

Number of duplicates: 35

In [6]:
# Drop duplicates
data = data.drop_duplicates()

# Verify removal
print(f"Data shape after removing duplicates: {data.shape}")

Data shape after removing duplicates: (29965, 21)

In [9]:
data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT1,BILL_AMT2,BILL_AMT3,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,3913.0,3102.0,689.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,2682.0,1725.0,2682.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,...,29239.0,14027.0,13559.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,...,46990.0,48233.0,49291.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,8617.0,5670.0,35835.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [11]:
data.shape

(29965, 21)

In [17]:
X = data.drop(columns=["default.payment.next.month"])

In [18]:
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,2,2,1,24,2,2,-1,-1,-2,-2,3913.0,3102.0,689.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,2,2,2,26,-1,2,0,0,0,2,2682.0,1725.0,2682.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,2,2,2,34,0,0,0,0,0,0,29239.0,14027.0,13559.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,2,2,1,37,0,0,0,0,0,0,46990.0,48233.0,49291.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,2,1,57,-1,0,-1,0,0,0,8617.0,5670.0,35835.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,3,1,39,0,0,0,0,0,0,188948.0,192815.0,208365.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,0,1683.0,1828.0,3502.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,2,2,37,4,3,2,-1,0,0,3565.0,3356.0,2758.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,3,1,41,1,-1,0,0,0,-1,-1645.0,78379.0,76304.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,2,1,46,0,0,0,0,0,0,47929.0,48905.0,49764.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [19]:
y = data["default.payment.next.month"]

In [20]:
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default.payment.next.month, Length: 29965, dtype: int64

In [21]:
 from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.25 , random_state=42)

In [28]:
X_train

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
11266,70000.0,2,2,1,34,2,2,2,2,2,2,16965.0,17398.0,18310.0,1000.0,1500.0,900.0,800.0,900.0,2000.0
14809,130000.0,1,1,1,45,2,0,0,2,2,2,53709.0,55244.0,58716.0,3000.0,5000.0,0.0,5000.0,1200.0,3000.0
3370,30000.0,1,2,2,36,0,0,0,0,0,0,36124.0,35538.0,34359.0,2500.0,2215.0,1156.0,1200.0,3000.0,3000.0
20178,300000.0,2,1,1,30,-2,-2,-2,-2,-2,-2,0.0,0.0,811.0,0.0,811.0,1128.0,1760.0,819.0,753.0
457,50000.0,1,1,2,32,-1,0,0,0,0,-2,23974.0,24131.0,25326.0,1800.0,1900.0,1300.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29836,180000.0,1,6,1,34,-2,-2,-2,-2,-2,-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5392,90000.0,1,2,2,28,2,0,0,0,2,2,18978.0,20675.0,23329.0,2000.0,3000.0,2000.0,0.0,3400.0,0.0
860,50000.0,1,1,2,26,-2,-2,-2,-2,-2,-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15807,280000.0,2,2,2,25,0,0,0,0,0,0,196909.0,176261.0,174573.0,6285.0,5897.0,5895.0,7747.0,6509.0,11234.0
23674,180000.0,2,2,1,38,-1,2,2,-1,0,0,7098.0,4089.0,0.0,0.0,0.0,8941.0,0.0,0.0,0.0

In [29]:
X_test

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
29334,100000.0,1,1,2,27,0,0,0,0,0,0,9228.0,10240.0,11372.0,1171.0,1303.0,1023.0,360.0,10000.0,442.0
24426,150000.0,1,1,1,40,-2,-1,-1,-1,0,0,0.0,1003.0,1003.0,1003.0,1003.0,35206.0,2000.0,18158.0,189000.0
9822,20000.0,1,3,2,49,0,0,0,-1,0,-1,19363.0,19609.0,-391.0,1200.0,160.0,20394.0,347.0,2110.0,12996.0
20887,420000.0,1,1,1,39,0,0,0,0,0,0,100333.0,102906.0,105030.0,5138.0,5267.0,5347.0,4019.0,4152.0,4173.0
21692,100000.0,2,5,2,27,0,0,0,0,0,0,152330.0,66107.0,60734.0,3000.0,2231.0,1617.0,1000.0,2000.0,590.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4070,200000.0,2,2,1,37,-2,-2,-2,-2,-2,-2,4157.0,601.0,432.0,606.0,432.0,1602.0,3017.0,937.0,1275.0
5637,200000.0,1,2,2,29,0,0,0,0,0,2,7468.0,34399.0,36792.0,30035.0,10008.0,15011.0,5010.0,153.0,14100.0
8895,450000.0,1,1,1,33,-1,-1,-1,-1,-1,-1,390.0,390.0,390.0,390.0,390.0,390.0,389.0,992.0,780.0
8381,60000.0,1,2,1,46,-1,0,-1,0,0,0,3046.0,286.0,6466.0,285.0,6466.0,3.0,5.0,10.0,15219.0
18078,450000.0,1,1,2,34,0,0,0,0,0,0,260733.0,228515.0,232762.0,20255.0,50171.0,7096.0,6604.0,10012.0,10000.0

In [30]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Define a pipeline for numerical data
num_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="mean")),  # Impute missing values with the mean
        ("scaler", StandardScaler()),                # Standardize numerical features
    ]
)

# Fit and transform your numerical data
X_scaled = num_pipeline.fit_transform(X)  # X is your input numerical DataFrame

In [31]:
X_scaled

array([[-1.13628477,  0.81015336,  0.18518609, ..., -0.30825283,
        -0.31433077, -0.29356226],
       [-0.3656192 ,  0.81015336,  0.18518609, ..., -0.24445373,
        -0.31433077, -0.18111857],
       [-0.59681887,  0.81015336,  0.18518609, ..., -0.24445373,
        -0.24891194, -0.01245303],
       ...,
       [-1.05921821, -1.23433421,  0.18518609, ..., -0.04029662,
        -0.1834931 , -0.11927454],
       [-0.67388543, -1.23433421,  1.45037102, ..., -0.18537577,
         3.15051247, -0.19213805],
       [-0.9050851 , -1.23433421,  0.18518609, ..., -0.24445373,
        -0.24891194, -0.23734041]])

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [52]:
y_pred = model.predict(X_test)

In [53]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 81.19%

In [54]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[5494  311]
 [1098  589]]

In [58]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd

In [59]:
# Initialize the XGBoost classifier
model2 = xgb.XGBClassifier(
    n_estimators=100,  # Number of boosting rounds
    learning_rate=0.1,  # Step size at each iteration
    max_depth=6,  # Maximum depth of a tree
    objective='binary:logistic',  # Binary classification (default or no default)
    eval_metric='logloss',  # Evaluation metric
    random_state=42
)

# Train the model
model2.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [60]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probability of the positive class (default)

In [61]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 81.19%
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      5805
           1       0.65      0.35      0.46      1687

    accuracy                           0.81      7492
   macro avg       0.74      0.65      0.67      7492
weighted avg       0.79      0.81      0.79      7492

Confusion Matrix:
[[5494  311]
 [1098  589]]

In [40]:
from sklearn.metrics import r2_score

In [49]:
r2 = r2_score(y_test, y_pred)
print("RÂ² Score:", r2)

RÂ² Score: 0.1890678298452826

In [35]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [62]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [63]:
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [None, 10, 20, 30],   # Depth of the trees
    'min_samples_split': [2, 5, 10],   # Minimum samples required to split a node
    'min_samples_leaf': [1, 2, 4],     # Minimum samples required at a leaf node
    'max_features': ['auto', 'sqrt', 'log2'],  # Number of features to consider at each split
    'bootstrap': [True, False]         # Whether bootstrap samples are used
}

In [66]:
from sklearn.model_selection import RandomizedSearchCV

In [67]:
param_grid = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'bootstrap': [True, False]
}

In [68]:
random_search = RandomizedSearchCV(estimator=RandomForestClassifier(random_state=42),
                                   param_distributions=param_grid,
                                   n_iter=20,  # Number of random combinations to sample
                                   cv=5,       # Cross-validation folds
                                   n_jobs=-1,   # Use all cores
                                   verbose=2,   # Verbosity for progress
                                   random_state=42, 
                                   scoring='accuracy')

In [69]:
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

e:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\env\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
20 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "e:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "e:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\env\lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "e:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\env\lib\site-packages\sklearn\base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "e:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\env\lib\site-packages\sklearn\utils\_param_validation.py", line 96, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
e:\Data_Science _master\ML\prac_project\Credit Card Default Prediction\env\lib\site-packages\sklearn\model_selection\_search.py:979: UserWarning: One or more of the test scores are non-finite: [0.82223093 0.81724725 0.8216524  0.82111839        nan 0.82076251
 0.82129642 0.82107398 0.81769203 0.82125196 0.82022849        nan
 0.82151894        nan        nan 0.81996155 0.82129643 0.81867115
 0.81889354 0.82142992]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [None, 10, 20, 30],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 400]},
                   random_state=42, scoring='accuracy', verbose=2)

In [70]:
print(f"Best Hyperparameters: {random_search.best_params_}")
best_model = random_search.best_estimator_

Best Hyperparameters: {'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 10, 'bootstrap': True}

In [71]:

# Make predictions with the best model
y_pred = best_model.predict(X_test)

In [72]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 81.39%
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      5805
           1       0.68      0.33      0.45      1687

    accuracy                           0.81      7492
   macro avg       0.75      0.64      0.67      7492
weighted avg       0.80      0.81      0.79      7492

Confusion Matrix:
[[5533  272]
 [1122  565]]